"""add_active_set_code_to_users

Revision ID: af412fc86ff3
Revises: c641d7ccab14
Create Date: 2026-02-18 17:26:43.768886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af412fc86ff3'
down_revision: Union[str, None] = 'c641d7ccab14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_set_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_set_code')
    # ### end Alembic commands ###
