"""Initial schema with sets cards users analyses tables

Revision ID: c641d7ccab14
Revises: 
Create Date: 2026-02-04 01:40:24.483458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c641d7ccab14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('main_deck', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sideboard', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('estimated_win_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_user_created', 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('mana_cost', sa.String(length=50), nullable=True),
    sa.Column('cmc', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('type_line', sa.String(length=255), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'set_id', name='uq_cards_name_set_id'),
    sa.UniqueConstraint('scryfall_id')
    )
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_table('card_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('win_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'source', 'format', name='uq_card_ratings_card_source_format')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_ratings')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_analyses_user_created', table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('users')
    op.drop_table('sets')
    # ### end Alembic commands ###
